spring.application.name=blogapi
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/blogapi
spring.datasource.username=root
spring.datasource.password=Pinglan@721
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

jwt.secretkey=mySecretKey123456789
jwt.expiration=3600000

server.port=8080